#!/usr/bin/env bash
# transfers a file from local to the user's remote home directory.
# accepts 4 parameters: 1. path to file to be transferred
#			2. ip of server we want to transfer to
#			3. username scp connects with
#			4. path to the SSH private key that scp uses

USAGE="Usage: 0-transfer-file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -lt 3 ] || [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
	echo "$USAGE"
elif [ -z "$4" ]; then

	FILE=$1
	IP=$2
	UNAME=$3

	scp -o StrictHostKeyChecking=no "$FILE" "$UNAME"@"$IP":~/

else
	FILE=$1
	IP=$2
	UNAME=$3
	KEY=$4

	scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$UNAME"@"$IP":~/

fi
