#!/usr/bin/env bash
#configures NGINX server so that /redirect_me is redirecting to another page

STRING="location / {\n}\n\nlocation /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n\n"

apt-get -y update
apt-get -y install nginx
sed -i "s/location\n.*\n.*\n.*/$STRING/g" /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
nginx 
