#!/usr/bin/env bash
#configures NGINX server so that /redirect_me is redirecting to another page

STRING="location / {\n}\n\nlocation /redirect_me {\nreturn 301 https://z-alx.tech/;\n}\n\nerror_page 404 /404.html;\n\nlocation /404.html {\nroot /var/www/html;\ninternal;\n}\n\n"

apt-get -y update
apt-get -y install nginx
sed -i "s/location\n.*\n.*\n.*/$STRING/g" /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
nginx 
