#!/usr/bin/env bash
# prints "Best School" 10 times

LIST="Best School
Best School
Best School
Best School
Best School
Best School
Best School
Best School
Best School
Best School
"

for i in $LIST; do echo "$i"; done
