#!/usr/bin/env bash
# displays the visitor IP along with the HTTP
# status code from the Apache log file.


awk '{ print $1,$9 }' apache-access.log | sort | uniq -c | sort -k 1nr | awk '{printf "    %-s %s %s\n", $1, $2, $3}'
