#!/usr/bin/env bash
# prints "Best School" 10 times

hours=0
minutes=1
while (( hours <= 12 ))
do
	echo "Hour: $hours"
	while (( minutes <= 59 ))
	do
		echo "$minutes"
		((minutes++))
	done
	minutes=1
	((hours++))
done
